import VersoManual
import VersoBlueprint
import DoubleRatchet.CKA.Figure3Game
import DoubleRatchet.Constructions.DDHCKA
import DoubleRatchet.Theorems.Theorem3

open Verso.Genre Manual
open Informal

#doc (Manual) "Paper-to-Lean Correspondence" =>
%%%
tag := "paper_to_lean"
%%%

:::group "correspondence_core"
How the paper's notation and definitions map to the Lean formalization.
:::

This chapter refines the standalone correspondence note in `doc/`. The goal is
not only to list names, but to explain why the Lean declarations are the right
translation of the paper's mathematics.

:::definition "notation_map" (parent := "correspondence_core")
The paper's multiplicative Diffie-Hellman notation is translated into Mathlib's
additive scalar-action notation. Concretely:

- `g^a` becomes `a • g`;
- a uniform draw `x <-$ S` becomes Lean's `$ᵗ`;
- the CKA challenge advantage is represented by
  `CKA.Figure3.figure3GuessAdvantage`;
- the DDH challenge advantage is represented by `ddhDistAdvantage`.
:::

:::definition "definition12_map" (lean := "CKA.CKAScheme") (parent := "correspondence_core")
Definition 12 of the paper becomes the Lean structure `CKA.CKAScheme`. The
paper's initialization, send, and receive algorithms are represented as the
fields `init`, `send`, and `recv`.
:::

:::definition "definition13_map" (lean := "CKA.Figure3.Figure3CKASecurePaper, CKA.Figure3.figure3GuessAdvantage") (parent := "correspondence_core")
Definition 13 is represented canonically by `Figure3CKASecurePaper` together
with `figure3GuessAdvantage`. These declarations expose the hidden-bit Figure 3
game rather than only a derived two-game presentation.
:::

The auxiliary predicates still matter, but they should be read in the right
order:

- `CKA.CKASecure` is the single-epoch warmup predicate;
- `CKA.CKASecureDelta` is the restricted multi-epoch auxiliary predicate;
- `CKA.Figure3.Figure3CKASecure` is the helper two-game version of the real
  Figure 3 surface.

:::definition "theorem3_map" (lean := "CKA.ddh_implies_cka_security_single_epoch, CKA.ddh_implies_figure3_cka_security") (parent := "correspondence_core")
The paper's Theorem 3 appears in two useful Lean forms: the single-epoch
epsilon wrapper `ddh_implies_cka_security_single_epoch` and the paper-facing
Figure 3 theorem `ddh_implies_figure3_cka_security`. The second is the one that
matches the statement readers should compare directly against the paper.
:::

One final translation point deserves emphasis. The paper writes the group as a
cyclic group generated by `g`. In the Lean development this is expressed by the
hypothesis `Function.Bijective (fun a => a • g)`. That hypothesis is what lets
the random DDH branch, which samples a scalar and then maps it through `a • g`,
match the CKA random branch, which samples uniformly from the group directly.
